#https://medium.com/@lestrrat/taming-google-container-builder-22a6dded155c
substitutions:
  _SERVICE_NAME: nbd-web-go
  _REGION: asia-northeast1
  _GOOGLE_CLOUD_PROJECT: arconomy-122603
  _SMTP_USERNAME: "ac@arconomy.digital"
  _SMTP_PASSWORD: 1lovejaffacakes
  _SMTP_HOST: smtp.gmail.com
  _SMTP_PORT: "587"
  _SMTP_SEND_TO: ashlee@naturalbydesign.com.au
  _INSIGHTLY_URL: https://api.na1.insightly.com/v3.1/Leads/
  _INSIGHTLY_APIKEY: e112fa8b-574f-44bd-b636-2340d5fe5c71

steps:
    #https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/#bonus-toggling-between-build-approaches
    #Build Builder
    - name: gcr.io/cloud-builders/docker
      id: 'build-builder'
      entrypoint: 'bash'
      args:
        - -c
        - |
          docker build \
          --target builder \
          --cache-from gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:builder \
          -t gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:builder .

    #Pull Last Runtime
    - name: 'gcr.io/cloud-builders/docker'
      id: 'pull-runtime-image-for-cache'
      entrypoint: 'bash'
      args:
        - -c
        - |
          docker pull gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:latest || exit 0

    #Build Runtime
    - name: gcr.io/cloud-builders/docker
      id: 'build-runtime-image'
      entrypoint: 'bash'
      args:
        - -c
        - |
          docker build \
          --cache-from gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:builder \
          --cache-from gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:latest \
          -t gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:latest \
          .

    - name: 'gcr.io/cloud-builders/docker'
      id: 'push-runtime-docker'
      entrypoint: 'bash'
      args:
        - -c
        - |
          docker push gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:$SHORT_SHA

    #Deploy to Cloud Run
    - name: gcr.io/cloud-builders/gcloud
      id: 'cloud-run-deployment'
      entrypoint: 'bash'
      args:
        - -c
        - |
          gcloud beta run deploy $_SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:$SHORT_SHA \
          --region $_REGION \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$_GOOGLE_CLOUD_PROJECT \
          --set-env-vars SMTP_USERNAME=$_SMTP_USERNAME \
          --set-env-vars SMTP_PASSWORD=$_SMTP_PASSWORD \
          --set-env-vars SMTP_HOST=$_SMTP_HOST \
          --set-env-vars SMTP_PORT=$_SMTP_PORT \
          --set-env-vars SMTP_SEND_TO=$_SMTP_SEND_TO \
          --set-env-vars INSIGHTLY_URL=$_INSIGHTLY_URL \
          --set-env-vars INSIGHTLY_APIKEY=$_INSIGHTLY_APIKEY \
          --allow-unauthenticated \
          --platform managed \
          --max-instances=10

images: ['gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:builder', 'gcr.io/$PROJECT_ID/nbd/$_SERVICE_NAME:latest']
